# Faça um programa que leia um numero inteiro e mostre a sua tabuada
n = int(input("insira um numero para ter a tabuada dele: "))
print()
print(n, 'x  1:', n*1)
print(n, 'x  2:', n*2)
print(n, 'x  3:', n*3)
print(n, 'x  4:', n*4)
print(n, 'x  5:', n*5)
print(n, 'x  6:', n*6)
print(n, 'x  7:', n*7)
print(n, 'x  8:', n*8)
print(n, 'x  9:', n*9)
print(n, 'x 10:', n*10)
print('-'*30)
#Outra forma de fazer:
num = int(input('digite um numero para ver a sua tabuada: '))
print('{} X {:2} = {}'.format(num, 1, num*1))
print('{} X {:2} = {}'.format(num, 2, num*2))
print('{} X {:2} = {}'.format(num, 3, num*3))
print('{} X {:2} = {}'.format(num, 4, num*4))
print('{} X {:2} = {}'.format(num, 5, num*5))
print('{} X {:2} = {}'.format(num, 6, num*6))
print('{} X {:2} = {}'.format(num, 7, num*7))
print('{} X {:2} = {}'.format(num, 8, num*8))
print('{} X {:2} = {}'.format(num, 9, num*9))
print('{} X {:2} = {}'.format(num, 10, num*10))