# CRIE UM PRGRAMA QUE LEIA A IDADE E O SEXO DE VÁRIAS PESSOAS. A CADA PESSOA CADASTRADA, O PROGRAMA DEVERA PERGUNTAR SE O USUÁRIO QUER OU NÃO CONTINUAR
# NO FINAL MOSTRE:
# A) QUANTAS PESSOAS TEM MAIS DE 18 ANOS
# B) QUANTOS HOMENS FORAM CADASTRADOS
# C) QUANTAS MULHERES TEM MENOS DE 20 ANOS