# CRIE UM PROGRAMA QUE SIMULE O FUNCIONAMENTO DE UM CAIXA ELETRÔNICO. NO INICIO, PERGUNTE AO USUÁRIO QUAL O VALOR A SER SACADO (NÚMERO INTEIRO)
# E O PROGRAMA VAI INFORMAR QUANTAS CÉDULAS DE CADA VALOR SERÃO ENTREGUES.
# OBS. CONSIDERE QUE O CAIXA POSSUI CÉDULAS DE R$50, R$20, R$10 E R$1.