nome = input("Qual o seu nome ? " )
print()
print ("muito prazer em te conhecer {}!".format(nome)) #Outra forma de imprimir uma atribuição para o usuário é utilizando o "{}".format, que vai substituir as chaves pela atribuição
print()
print (nome, "agora me informe sua data de nascimento: ")
print()
dia = input("qual o dia que voce nasceu ? ")
mes = input("qual o mes que você nasceu ? (em extenso por favor) ")
ano = input("qual o ano que você nasceu ? ")
print()
print("certo,", nome, "então você nasceu no dia", dia, "de", mes, "de", ano)
print()
print ("Obrigado pelas informações, agora informe dois numeros que eu irei multiplica-los pra você")
print()
num1 = int(input("insira o primeiro numero: "))
num2 = int(input("insira o segundo numero: "))
res = num1 * num2
print()
print(nome, "a multiplicação de {} por {} é: {}".format(num1, num2, res))
